### ISSUE TITLE
Error when installing clipspy with Python 2.7

### ISSUE THREAD

**Issue by gitttt** [noxdafox/clipspy#4]
The pip installation worked fine with Python 3.7.
However, the same commands (`pip install clipspy)` cause the below error.
```
C:\Users\vagrant>pip install clipspy
Collecting clipspy
  Downloading https://files.pythonhosted.org/packages/e2/66/f31407774ee4dc486de406cdc84dbaf32af1a41037ebfb3c5c22d950d6e2/clipspy-0.2.4-cp37-cp37m-win_amd64.whl (476kB)
    100% |████████████████████████████████| 481kB 2.2MB/s
Collecting cffi>=1.0.0 (from clipspy)
  Downloading https://files.pythonhosted.org/packages/ca/f2/e375b7469a2dfe9d1feac81a10df97f18cd771b9a10ac62ca9864b760f7c/cffi-1.11.5-cp37-cp37m-win_amd64.whl (165kB)
    100% |████████████████████████████████| 174kB 6.5MB/s
Collecting pycparser (from cffi>=1.0.0->clipspy)
  Using cached https://files.pythonhosted.org/packages/8c/2d/aad7f16146f4197a11f8e91fb81df177adcc2073d36a17b1491fd09df6ed/pycparser-2.18.tar.gz
Installing collected packages: pycparser, cffi, clipspy
  Running setup.py install for pycparser ... done
Successfully installed cffi-1.11.5 clipspy-0.2.4 pycparser-2.18
You are using pip version 10.0.1, however version 18.0 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

C:\Users\vagrant>python
Python 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import clipspy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'clipspy'
>>> import clips
>>> exit()

C:\Users\vagrant>c:\Python27\Scripts\pip.exe install clipspy
Collecting clipspy
  Using cached https://files.pythonhosted.org/packages/d2/e9/5c3b0e9b6f504c24de16f2a37bea8fe872e9f66edcf1fea2b7d235a310cd/clipspy-0.2.4.tar.gz
Requirement already satisfied: cffi>=1.0.0 in c:\python27\lib\site-packages (from clipspy) (1.11.5)
Requirement already satisfied: enum34 in c:\python27\lib\site-packages (from clipspy) (1.1.6)
Requirement already satisfied: pycparser in c:\python27\lib\site-packages (from cffi>=1.0.0->clipspy) (2.18)
Installing collected packages: clipspy
  Running setup.py install for clipspy ... error
    Complete output from command c:\python27\python.exe -u -c "import setuptools, tokenize;__file__='c:\\users\\vagrant\\appdata\\local\\temp\\1\\pip-install-bl5so9\\clipspy\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record c:\users\vagrant\appdata\local\temp\1\pip-record-ikrdz6\install-record.txt --single-version-externally-managed --compile:
    fatal: Not a git repository (or any of the parent directories): .git
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-2.7
    creating build\lib.win-amd64-2.7\clips
    copying clips\agenda.py -> build\lib.win-amd64-2.7\clips
    copying clips\classes.py -> build\lib.win-amd64-2.7\clips
    copying clips\clips_build.py -> build\lib.win-amd64-2.7\clips
    copying clips\common.py -> build\lib.win-amd64-2.7\clips
    copying clips\data.py -> build\lib.win-amd64-2.7\clips
    copying clips\environment.py -> build\lib.win-amd64-2.7\clips
    copying clips\error.py -> build\lib.win-amd64-2.7\clips
    copying clips\facts.py -> build\lib.win-amd64-2.7\clips
    copying clips\functions.py -> build\lib.win-amd64-2.7\clips
    copying clips\modules.py -> build\lib.win-amd64-2.7\clips
    copying clips\router.py -> build\lib.win-amd64-2.7\clips
    copying clips\__init__.py -> build\lib.win-amd64-2.7\clips
    running build_ext
    generating cffi module 'build\\temp.win-amd64-2.7\\Release\\_clips.c'
    creating build\temp.win-amd64-2.7
    creating build\temp.win-amd64-2.7\Release
    building '_clips' extension
    creating build\temp.win-amd64-2.7\Release\build
    creating build\temp.win-amd64-2.7\Release\build\temp.win-amd64-2.7
    creating build\temp.win-amd64-2.7\Release\build\temp.win-amd64-2.7\Release
    C:\Users\vagrant\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\amd64\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -I/usr/include/clips -I/usr/local/include/clips -Ic:\python27\include -Ic:\python27\PC /Tcbuild\temp.win-amd64-2.7\Release\_clips.c /Fobuild\temp.win-amd64-2.7\Release\build\temp.win-amd64-2.7\Release\_clips.obj
    _clips.c
    build\temp.win-amd64-2.7\Release\_clips.c(523) : fatal error C1083: Cannot open include file: 'clips.h': No such file or directory
    error: command 'C:\\Users\\vagrant\\AppData\\Local\\Programs\\Common\\Microsoft\\Visual C++ for Python\\9.0\\VC\\Bin\\amd64\\cl.exe' failed with exit status 2

    ----------------------------------------
Command "c:\python27\python.exe -u -c "import setuptools, tokenize;__file__='c:\\users\\vagrant\\appdata\\local\\temp\\1\\pip-install-bl5so9\\clipspy\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record c:\users\vagrant\appdata\local\temp\1\pip-record-ikrdz6\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in c:\users\vagrant\appdata\local\temp\1\pip-install-bl5so9\clipspy\
```

**Comment by noxdafox** [comment]
I tried several further attempts but with no avail. My suspect is that I compiled the lib with a too recent version of VS and I am unable to compile against Python 2.

I also tried to link against the `legacy_stdio_definitions` libraries as recommended by the [documentation](https://msdn.microsoft.com/en-us/library/mt743084.aspx) but it did not help.

I compiled further wheels extending [installation support](https://pypi.org/project/clipspy/#files) to all mayor versions of Python 3. I think this is more than enough.

In case you find a way around this which would not require to install old versions of VS please share. 

Considering Pyhton 2 is going towards deprecation I would consider this a low priority issue.

**Comment by gitttt** [comment]
No problem. I just wasn't sure what the problem was. Could have been some minor issue that could have been fixed easily. Python3 is great.

**Comment by gitttt** [comment]
Got it to work on Windows Server 2016 and Python 2.7.13

- Install https://download.microsoft.com/download/7/9/6/796EF2E4-801B-4FC4-AB28-B59FBF6D907B/VCForPython27.msi

- Download and extract the clips 6.30 sources, link [here],(https://sourceforge.net/projects/clipsrules/files/CLIPS/6.30/clips_core_source_630.zip).
I am extracting them into `c:\tmp\clips_core_source_630`
- Open a terminal, e.g. `cmd.exe`
- `cd c:\tmp\clips_core_source_630`
- `copy c:\tmp\clips_core_source_630\makefiles\makefile.win c:\tmp\clips_core_source_630\core`
- `"c:\Users\<your username>\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\vcvarsall.bat" amd64`
- `cd c:\tmp\clips_core_source_630\core`
- `nmake -f makefile.win`
- `lib.exe /OUT:clips.lib *.obj`
- cd c:\tmp
- `git clone https://github.com/noxdafox/clipspy.git`
- `cd clipspy`
- `python setup.py build_ext --include-dirs c:\tmp\clips_core_source_630\core --library-dirs c:\tmp\clips_core_source_630\core`
- `pip install wheel`
- `python setup.py sdist bdist_wheel`

**Comment by noxdafox** [comment]
I'd like to try the suggested method and add it as well in the documentation if it works.

I'll keep the issue open until then as a memo. Yet a low level priority task.

**Comment by noxdafox** [comment]
Tried your suggestion above and still get lots of linking errors, I suspect VS2017 is the culprit.

I will try later on with an older version of VS.

**Comment by noxdafox** [comment]
With the release of `clipspy` `1.0.0` Python 2 is no longer supported.
